1.0.2

diff --git a/git-sync b/git-sync
--- a/git-sync
+++ b/git-sync
@@ -43,23 +43,23 @@ DEFAULT_AUTOCOMMIT_CMD="git add -u ; git commit -m \"%message\";"
 ALL_AUTOCOMMIT_CMD="git add -A ; git commit -m \"%message\";"
 
 # default commit message substituted into autocommit commands
-DEFAULT_AUTOCOMMIT_MSG="changes from $(uname -n) on $(date)"
+DEFAULT_AUTOCOMMIT_MSG="modifications de $(uname -n) le $(date)"
 
 
-# AUTOCOMMIT_CMD="echo \"Please commit or stash pending changes\"; exit 1;"
+# AUTOCOMMIT_CMD="echo \"Veuillez valider ou stasher les modifications en attente\"; exit 1;"
 # TODO mode for stash push & pop
 
 print_usage() {
     cat << EOF
 usage: $0 [-h] [-n] [-s] [MODE]
 
-Synchronize the current branch to a remote backup
-MODE may be either "sync" (the default) or "check", to verify that the branch is ready to sync
+Synchroniser la branche actuelle avec une sauvegarde distante
+MODE peut être soit "sync" (par défaut) soit "check", pour vérifier que la branche est prête à être synchronisée
 
-OPTIONS:
-   -h      Show this message
-   -n      Commit new files even if branch.\$branch_name.syncNewFiles isn't set
-   -s      Sync the branch even if branch.\$branch_name.sync isn't set
+OPTIONS :
+   -h      Afficher ce message
+   -n      Valider les nouveaux fichiers même si branch.\$branch_name.syncNewFiles n'est pas défini
+   -s      Synchroniser la branche même si branch.\$branch_name.sync n'est pas défini
 EOF
 }
 sync_new_files_anyway="false"
@@ -93,56 +93,56 @@ __log_msg()
 # echo the git dir
 __gitdir()
 {
-	if [ "true" = "$(git rev-parse --is-inside-work-tree "$PWD" | head -1)" ]; then
-		git rev-parse --git-dir "$PWD" 2>/dev/null
-	fi
+        if [ "true" = "$(git rev-parse --is-inside-work-tree "$PWD" | head -1)" ]; then
+                git rev-parse --git-dir "$PWD" 2>/dev/null
+        fi
 }
 
 # echos repo state
 git_repo_state ()
 {
-	local g="$(__gitdir)"
-	if [ -n "$g" ]; then
-		if [ -f "$g/rebase-merge/interactive" ]; then
-			echo "REBASE-i"
-		elif [ -d "$g/rebase-merge" ]; then
-			echo "REBASE-m"
-		else
-			if [ -d "$g/rebase-apply" ]; then
-				echo "AM/REBASE"
-			elif [ -f "$g/MERGE_HEAD" ]; then
-				echo "MERGING"
-			elif [ -f "$g/CHERRY_PICK_HEAD" ]; then
-				echo "CHERRY-PICKING"
-			elif [ -f "$g/BISECT_LOG" ]; then
-				echo "BISECTING"
-			fi
-		fi
-		if [ "true" = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]; then
-			if [ "true" = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]; then
-				echo "|BARE"
-			else
-				echo "|GIT_DIR"
-			fi
-		elif [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
-			git diff --no-ext-diff --quiet --exit-code || echo "|DIRTY"
-#			if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ]; then
-#			        git rev-parse --verify refs/stash >/dev/null 2>&1 && s="$"
-#			fi
+        local g="$(__gitdir)"
+        if [ -n "$g" ]; then
+                if [ -f "$g/rebase-merge/interactive" ]; then
+                        echo "REBASE-i"
+                elif [ -d "$g/rebase-merge" ]; then
+                        echo "REBASE-m"
+                else
+                        if [ -d "$g/rebase-apply" ]; then
+                                echo "AM/REBASE"
+                        elif [ -f "$g/MERGE_HEAD" ]; then
+                                echo "FUSION"
+                        elif [ -f "$g/CHERRY_PICK_HEAD" ]; then
+                                echo "CHERRY-PICKING"
+                        elif [ -f "$g/BISECT_LOG" ]; then
+                                echo "BISECTING"
+                        fi
+                fi
+                if [ "true" = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]; then
+                        if [ "true" = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]; then
+                                echo "|BARE"
+                        else
+                                echo "|GIT_DIR"
+                        fi
+                elif [ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
+                        git diff --no-ext-diff --quiet --exit-code || echo "|SALE"
+#                        if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ]; then
+#                                git rev-parse --verify refs/stash >/dev/null 2>&1 && s="$"
+#                        fi
 #
-#			if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ]; then
-#			   if [ -n "$(git ls-files --others --exclude-standard)" ]; then
-#			      u="%"
-#			   fi
-#			fi
+#                        if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ]; then
+#                           if [ -n "$(git ls-files --others --exclude-standard)" ]; then
+#                              u="%"
+#                           fi
+#                        fi
 #
-#			if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
-#				__git_ps1_show_upstream
-#			fi
-		fi
-	else
-	    echo "NOGIT"
-	fi
+#                        if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
+#                                __git_ps1_show_upstream
+#                        fi
+                fi
+        else
+            echo "PAS DE GIT"
+        fi
 }
 
 # check if we only have untouched, modified or (if configured) new files
@@ -150,15 +150,15 @@ check_initial_file_state()
 {
     local syncNew="$(git config --get --bool branch.$branch_name.syncNewFiles)"
     if [[ "true" == "$syncNew" || "true" == "$sync_new_files_anyway" ]]; then
-	# allow for new files
-	if [ ! -z "$(git status --porcelain | grep -E '^[^ \?][^M\?] *')" ]; then
-	    echo "NonNewOrModified"
-	fi
+        # allow for new files
+        if [ ! -z "$(git status --porcelain | grep -E '^[^ \?][^M\?] *')" ]; then
+            echo "NonNouveauOuModifié"
+        fi
     else
-	# also bail on new files
-	if [ ! -z "$(git status --porcelain | grep -E '^[^ ][^M] *')" ]; then
-	    echo "NotOnlyModified"
-	fi
+        # also bail on new files
+        if [ ! -z "$(git status --porcelain | grep -E '^[^ ][^M] *')" ]; then
+            echo "NonSeulementModifié"
+        fi
     fi
 }
 
@@ -167,7 +167,7 @@ check_initial_file_state()
 local_changes()
 {
     if [ ! -z "$(git status --porcelain | grep -E '^(\?\?|[MARC] |[ MARC][MD])*')" ]; then
-	echo "LocalChanges"
+        echo "ModificationsLocales"
     fi
 }
 
@@ -177,38 +177,38 @@ sync_state()
     local count="$(git rev-list --count --left-right $remote_name/$branch_name...HEAD)"
 
     case "$count" in
-	"") # no upstream
-	    echo "noUpstream"
-	    false
-	    ;;
-	"0	0")
-	    echo "equal"
-	    true
-	    ;;
-	"0	"*)
-	    echo "ahead"
-	    true
-	    ;;
-	*"	0")
-	    echo "behind"
-	    true
-	    ;;
-	*)
-	    echo "diverged"
-	    true
-	    ;;
+        "") # no upstream
+            echo "pas de flux amont"
+            false
+            ;;
+        "0        0")
+            echo "égal"
+            true
+            ;;
+        "0        "*)
+            echo "en avance"
+            true
+            ;;
+        *"        0")
+            echo "en retard"
+            true
+            ;;
+        *)
+            echo "divergé"
+            true
+            ;;
     esac
 }
 
 # exit, issue warning if not in sync
 exit_assuming_sync() {
     if [ "equal" == "$(sync_state)" ] ; then
-	__log_msg "In sync, all fine."
-	exit 0;
+        __log_msg "Synchronisé, tout va bien."
+        exit 0;
     else
-	__log_msg "Synchronization FAILED! You should definitely check your repository carefully!"
-	__log_msg "(Possibly a transient network problem? Please try again in that case.)"
-	exit 3
+        __log_msg "Échec de la synchronisation ! Vous devriez vérifier votre dépôt attentivement !"
+        __log_msg "(Peut-être un problème réseau temporaire ? Veuillez réessayer dans ce cas.)"
+        exit 3
     fi
 }
 
@@ -218,13 +218,13 @@ exit_assuming_sync() {
 
 # first some sanity checks
 rstate="$(git_repo_state)"
-if [[ -z "$rstate" || "|DIRTY" = "$rstate" ]]; then
-    __log_msg "Preparing. Repo in $(__gitdir)"
-elif [[ "NOGIT" = "$rstate" ]] ; then
-    __log_msg "No git repository detected. Exiting."
+if [[ -z "$rstate" || "|SALE" = "$rstate" ]]; then
+    __log_msg "Préparation. Dépôt dans $(__gitdir)"
+elif [[ "PAS DE GIT" = "$rstate" ]] ; then
+    __log_msg "Aucun dépôt git détecté. Sortie."
     exit 128 # matches git's error code
 else
-    __log_msg "Git repo state considered unsafe for sync: $(git_repo_state)"
+    __log_msg "État du dépôt git considéré comme non sécurisé pour la synchronisation : $(git_repo_state)"
     exit 2
 fi
 
@@ -233,7 +233,7 @@ branch_name=$(git symbolic-ref -q HEAD)
 branch_name=${branch_name##refs/heads/}
 
 if [ -z "$branch_name" ] ; then
-    __log_msg "Syncing is only possible on a branch."
+    __log_msg "La synchronisation n'est possible que sur une branche."
     git status
     exit 2
 fi
@@ -248,30 +248,30 @@ if [ -z "$remote_name" ] ; then
 fi
 
 if [ -z "$remote_name" ] ; then
-    __log_msg "the current branch does not have a configured remote."
+    __log_msg "la branche actuelle n'a pas de distant configuré."
     echo
-    __log_msg "Please use"
+    __log_msg "Veuillez utiliser"
     echo
     __log_msg "  git branch --set-upstream-to=[remote_name]/$branch_name"
     echo
-    __log_msg "replacing [remote_name] with the name of your remote, i.e. - origin"
-    __log_msg "to set the remote tracking branch for git-sync to work"
+    __log_msg "en remplaçant [remote_name] par le nom de votre distant, c'est-à-dire - origin"
+    __log_msg "pour définir la branche de suivi distante pour que git-sync fonctionne"
     exit 2
 fi
 
 # check if current branch is configured for sync
 if [[ "true" != "$(git config --get --bool branch.$branch_name.sync)" && "true" != "$sync_anyway" ]] ; then
     echo
-    __log_msg "Please use"
+    __log_msg "Veuillez utiliser"
     echo
     __log_msg "  git config --bool branch.$branch_name.sync true"
     echo
-    __log_msg "to enlist branch $branch_name for synchronization."
-    __log_msg "Branch $branch_name has to have a same-named remote branch"
-    __log_msg "for git-sync to work."
+    __log_msg "pour inscrire la branche $branch_name pour la synchronisation."
+    __log_msg "La branche $branch_name doit avoir une branche distante du même nom"
+    __log_msg "pour que git-sync fonctionne."
     echo
-    __log_msg "(If you don't know what this means, you should change that"
-    __log_msg "before relying on this script. You have been warned.)"
+    __log_msg "(Si vous ne savez pas ce que cela signifie, vous devriez changer cela"
+    __log_msg "avant de vous fier à ce script. Vous avez été averti.)"
     echo
     exit 1
 fi
@@ -282,24 +282,24 @@ if [[ -z "$1" || "$1" == "sync" ]]; then
 elif [[ "check" == "$1" ]]; then
     mode="check"
 else
-    __log_msg "Mode $1 not recognized"
+    __log_msg "Mode $1 non reconnu"
     exit 100
 fi
 
 __log_msg "Mode $mode"
 
-__log_msg "Using $remote_name/$branch_name"
+__log_msg "Utilisation de $remote_name/$branch_name"
 
 # check for intentionally unhandled file states
 if [ ! -z "$(check_initial_file_state)" ] ; then
-    __log_msg "There are changed files you should probably handle manually."
+    __log_msg "Il y a des fichiers modifiés que vous devriez probablement gérer manuellement."
     git status
     exit 1
 fi
 
 # if in check mode, this is all we need to know
 if [ $mode == "check" ] ; then
-    __log_msg "check OK; sync may start."
+    __log_msg "vérification OK; la synchronisation peut commencer."
     exit 0
 fi
 
@@ -310,9 +310,9 @@ if [ ! -z "$(local_changes)" ]; then
 
     # discern the three ways to auto-commit
     if [ ! -z "$config_autocommit_cmd" ]; then
-	autocommit_cmd="$config_autocommit_cmd"
+        autocommit_cmd="$config_autocommit_cmd"
     elif [[ "true" == "$(git config --get --bool branch.$branch_name.syncNewFiles)" || "true" == "$sync_new_files_anyway" ]]; then
-	autocommit_cmd=${ALL_AUTOCOMMIT_CMD}
+        autocommit_cmd=${ALL_AUTOCOMMIT_CMD}
     else
         autocommit_cmd=${DEFAULT_AUTOCOMMIT_CMD}
     fi
@@ -323,65 +323,65 @@ if [ ! -z "$(local_changes)" ]; then
     fi
     autocommit_cmd=$(echo "$autocommit_cmd" | sed "s/%message/$commit_msg/")
 
-    __log_msg "Committing local changes using ${autocommit_cmd}"
+    __log_msg "Validation des modifications locales en utilisant ${autocommit_cmd}"
     eval $autocommit_cmd
 
     # after autocommit, we should be clean
     rstate="$(git_repo_state)"
     if [[ ! -z "$rstate" ]]; then
-	__log_msg "Auto-commit left uncommitted changes. Please add or remove them as desired and retry."
-	exit 1
+        __log_msg "L'auto-commit a laissé des modifications non validées. Veuillez les ajouter ou les supprimer comme souhaité et réessayer."
+        exit 1
     fi
 fi
 
 # fetch remote to get to the current sync state
 # TODO make fetching/pushing optional
-__log_msg "Fetching from $remote_name/$branch_name"
+__log_msg "Récupération depuis $remote_name/$branch_name"
 git fetch $remote_name $branch_name
 if [ $? != 0 ] ; then
-    __log_msg "git fetch $remote_name returned non-zero. Likely a network problem; exiting."
+    __log_msg "git fetch $remote_name a retourné une valeur non nulle. Probablement un problème de réseau ; sortie."
     exit 3
 fi
 
 case "$(sync_state)" in
-"noUpstream")
-	__log_msg "Strange state, you're on your own. Good luck."
-	exit 2
-	;;
-"equal")
-	exit_assuming_sync
-	;;
-"ahead")
-	__log_msg "Pushing changes..."
-	git push $remote_name $branch_name:$branch_name
-	if [ $? == 0 ]; then
-	    exit_assuming_sync
-	else
-	    __log_msg "git push returned non-zero. Likely a connection failure."
-	    exit 3
-	fi
-	;;
-"behind")
-	__log_msg "We are behind, fast-forwarding..."
-	git merge --ff --ff-only $remote_name/$branch_name
-	if [ $? == 0 ]; then
-	    exit_assuming_sync
-	else
-	    __log_msg "git merge --ff --ff-only returned non-zero ($?). Exiting."
-	    exit 2
-	fi
-	;;
-"diverged")
-	__log_msg "We have diverged. Trying to rebase..."
-	git rebase $remote_name/$branch_name
-	if [[ $? == 0 && -z "$(git_repo_state)" && "ahead" == "$(sync_state)" ]] ; then
-	    __log_msg "Rebasing went fine, pushing..."
-	    git push $remote_name $branch_name:$branch_name
-	    exit_assuming_sync
-	else
-	    __log_msg "Rebasing failed, likely there are conflicting changes. Resolve them and finish the rebase before repeating git-sync."
-	    exit 1
-	fi
-	# TODO: save master, if rebasing fails, make a branch of old master
-	;;
+"pas de flux amont")
+        __log_msg "État étrange, vous êtes seul. Bonne chance."
+        exit 2
+        ;;
+"égal")
+        exit_assuming_sync
+        ;;
+"en avance")
+        __log_msg "Envoi des modifications..."
+        git push $remote_name $branch_name:$branch_name
+        if [ $? == 0 ]; then
+            exit_assuming_sync
+        else
+            __log_msg "git push a retourné une valeur non nulle. Probablement une défaillance de connexion."
+            exit 3
+        fi
+        ;;
+"en retard")
+        __log_msg "Nous sommes en retard, avancement rapide..."
+        git merge --ff --ff-only $remote_name/$branch_name
+        if [ $? == 0 ]; then
+            exit_assuming_sync
+        else
+            __log_msg "git merge --ff --ff-only a retourné une valeur non nulle ($?). Sortie."
+            exit 2
+        fi
+        ;;
+"divergé")
+        __log_msg "Nous avons divergé. Tentative de rebase..."
+        git rebase $remote_name/$branch_name
+        if [[ $? == 0 && -z "$(git_repo_state)" && "ahead" == "$(sync_state)" ]] ; then
+            __log_msg "Le rebase s'est bien passé, envoi..."
+            git push $remote_name $branch_name:$branch_name
+            exit_assuming_sync
+        else
+            __log_msg "Le rebase a échoué, il y a probablement des modifications conflictuelles. Résolvez-les et terminez le rebase avant de répéter git-sync."
+            exit 1
+        fi
+        # TODO: save master, if rebasing fails, make a branch of old master
+        ;;
 esac
