Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,90 +1,147 @@
 #!/data/data/com.termux/files/usr/bin/bash
-source /data/data/com.termux/files/usr/etc/bash.bashrc
+source /storage/emulated/0/Documents/Repository/OhMyObsidian/bashrc
 
-LOCK_FILE="$HOME/sync-vaults.lock"
+### Turn off untrusted repo protection
 
-# Function to remove lock file
-cleanup() {
-    rm -f "$LOCK_FILE"
-    exit 1
-}
+existing_dirs=$(git config --global --get-all safe.directory)
 
-# Trap to catch interruptions
-trap cleanup INT TERM
-
-# Function to wait for lock release
-wait_for_lock_release() {
-    while [ -e "$LOCK_FILE" ]; do
-        sleep 1
-    done
-}
-
-if [ -e "$LOCK_FILE" ]; then # check if the lock file exists
-    if [ -z "$(ps -p $(cat "$LOCK_FILE") -o pid=)" ]; then # Check if the process that created the lockfile is still running
-        echo "Removing stale lock file."
-        rm -f "$LOCK_FILE"
-    else
-        wait_for_lock_release
-    fi
+if [[ ! $existing_dirs == *"*"* ]]; then
+    git config --global --add safe.directory "*"
 fi
 
-# Store the PID in the lock file
-echo $$ > "$LOCK_FILE"
+### Update scripts repo
 
-skip_pause_val="--skip-pause"
+cd "$SCRIPTS_REPO_PATH"
+git fetch > /dev/null
+git_status=$(git status)
 
-source "$HOME/log_helper.sh"
-log_file="$HOME/sync.log"
-setup_logging $log_file
+if [[ "$git_status" == *"Your branch is behind"* ]]; then
+  if [[ "$git_status" == *"Changes not staged for commit"* || "$git_status" == *"Changes to be committed"* ]]; then
+    echo -e "${RED}There are local changes in the scripts repo which would block a git pull. Just be aware that you're missing updates. Continuing script...${RESET}"
+  else
+    if git pull > /dev/null 2>&1; then
+      echo -e "${GREEN}Updated the scripts repo!${RESET}"
+    else
+      echo -e "${RED}Failed to update the scripts repo.${RESET}"
+      exit 1
+    fi
 
-cmd () {
-  printf "\n\033[0;34m%s\033[0m\n" "$(basename "$PWD")"
-  $HOME/git-sync -ns 2>&1 | tee $LAST_SYNC_PATH
-
-  if [ $? -ne 0 ]; then
-        cat $LAST_SYNC_PATH >> $NOTIFICATION_PATH # Send notifcation
-  fi
-}
-
-git_repos=()
-
-# Populate the array with Git repos from the Obsidian folder
-for dir in "$OBSIDIAN_DIR_PATH"/*; do
-  if [ -d "$dir" ]; then
-    cd "$dir"
-    if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-      git_repos+=("$dir")
+    # Check if 'setup' file in repo is different from the one in $HOME
+    if ! diff "${SCRIPTS_REPO_PATH}/setup" "$HOME/OhMyObsidian/setup" > /dev/null; then
+        cmd="cp \"${SCRIPTS_REPO_PATH}/setup\" \"${HOME}/OhMyObsidian/\""
+        echo -e "$cmd" | termux-clipboard-set
+        echo -e "${RED}The 'setup' file has been updated.\nRun the following command to update it (it's already in your clipboard):\n${YELLOW}${cmd}${RESET}"
+        echo -e "${RED}Exiting script.${RESET}"
+        exit 1
     fi
   fi
+fi
+
+### Make sure Termux has file permissions
+
+if touch "$STORAGE_PATH"/.termux_permission_check; then
+  rm "$STORAGE_PATH"/.termux_permission_check
+else
+  echo -e "${RED}Termux does not have file permissions.${RESET}"
+  echo -e "${BLUE}Run 'termux-setup-storage' or give the permission from Termux's permissions menu on Android.${RESET}"
+fi
+
+### Enable allow-external-apps
+
+if grep -q '^# allow-external-apps = true' $HOME/.termux/termux.properties; then
+  sed -i 's/^# allow-external-apps = true/allow-external-apps = true/' $HOME/.termux/termux.properties
+  termux-reload-settings
+fi
+
+### Install packages -- attempt
+
+# package_installed() {
+#   dpkg -l | grep -q "$1"
+# }
+
+# for pkg in git termux-api openssh; do
+#   if ! package_installed "$pkg"; then
+#     echo "Installing $pkg..."
+#     apt-get install -y "$pkg"
+#   fi
+# done
+
+### Create SSH keys
+
+if [ ! -f ~/.ssh/id_rsa ]; then
+  echo -e "${BLUE}Creating an SSH key...${RESET}"
+  ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa > /dev/null
+
+  if cat ~/.ssh/id_rsa.pub | termux-clipboard-set; then
+    echo -e "${BLUE}SSH public key has been copied to your clipboard.${RESET}"
+    echo -e "${BLUE}Please paste it into your Git host's SSH keys authentication settings.${RESET}"
+  else
+    echo -e "$YELLOW"
+    cat ~/.ssh/id_rsa.pub
+    echo -e "\n$RESET"
+    echo -e "${BLUE}Copy the key above (in ${YELLOW}yellow${BLUE}) and paste it into your Git host's SSH keys authentication settings.${RESET}"
+  fi
+else
+  echo -e "$YELLOW"
+  cat ~/.ssh/id_rsa.pub
+  echo -e "\n${BLUE}Here's your SSH key (above in ${YELLOW}yellow${BLUE}) in case you want to copy it.${RESET}"
+fi
+
+### Copy and chmod scripts to $HOME
+
+DEST_DIR="$HOME/OhMyObsidian"
+
+for file in "$SCRIPTS_REPO_PATH"/*; do
+  filename=$(basename -- "$file")
+  cp "$file" "$DEST_DIR/"
+  chmod +x "$DEST_DIR/$filename"
 done
 
-msg="You can try running 'setup' to see if it helps".
+### Add source to bashrc
 
-# Exit if no Git repos are found
-if [ ${#git_repos[@]} -eq 0 ]; then
-  echo -e "${YELLOW}No Git repositories found in the Obsidian folder.\n${msg}${RESET}"
-  exit 1
+BASHRC_FILE="/data/data/com.termux/files/usr/etc/bash.bashrc"
+
+declare -a LINES_TO_ADD=(
+  "source $SCRIPTS_REPO_PATH/bashrc # obsidian-sync-source-tag"
+)
+
+modify_or_add_line_with_tag() {
+  local line=$1
+  local file=$2
+  local tag=$(echo "$line" | awk -F'#' '{print $2}')
+
+  sed -i "/$tag/d" "$file"
+  echo "$line" >> "$file"
+}
+
+for line in "${LINES_TO_ADD[@]}"; do
+  modify_or_add_line_with_tag "$line" "$BASHRC_FILE"
+done
+
+### Make sure user.name and user.email is populated
+
+git_name=$(git config --global user.name)
+git_email=$(git config --global user.email)
+
+if [ -z "$git_name" ]; then
+  read -p "Enter your git user.name: " git_name
+  git config --global user.name "$git_name"
 fi
 
-if [[ -n "$1" && "$1" != "$skip_pause_val" ]]; then # Sync a single repo
-  if [[ " ${git_repos[@]} " =~ " $OBSIDIAN_DIR_PATH/$1 " ]]; then
-    (cd "$OBSIDIAN_DIR_PATH/$1" && cmd)
-  else
-    echo -e "${RED}Specified directory doesn't exist or is not a Git repository.\n${msg}${RESET}"
-    exit 1
-  fi
-else  # Sync all Git repos
-  for repo in "${git_repos[@]}"; do
-    (cd "$repo" && cmd)
-  done
+ if [ -z "$git_email" ]; then
+  read -p "Enter your git user.email: " git_email
+  git config --global user.email "$git_email"
 fi
 
-log_cleanup $log_file
+### Git config
 
-if [[ -z "$1" ]]; then
-  bypass_log "echo -e '\n\033[44;97mPress enter to finish...\033[0m' && read none"
-fi
+git config --global core.editor nano
+git config --global merge.conflictstyle diff3
 
+###
 
-rm -f "$LOCK_FILE"
-exit 0
+touch $NOTIFICATION_PATH
+
+cd $OBSIDIAN_DIR_PATH
+
+echo -e "\n${GREEN}Setup complete${RESET}\n"
